name: triple
description: Abstraction for the Segmented State Pattern. Use to create Triple Store. 
version: 2.0.0
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  async: ">=2.6.1 <3.0.0"

dev_dependencies:
  test: ^1.16.5
  flutterando_analysis: ^0.0.2
