name: triple
description: abstraction for the Segmented State Pattern
version: 0.0.26
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  async: ^2.5.0-nullsafety.3
  dartz: ^0.10.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.13
