name: search
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.0
  async: ^2.5.0-nullsafety.3
  flutter_mobx: ^2.0.0-nullsafety.0
  flutter_triple: ^1.0.0
  mobx_triple: ^1.0.0
  mobx: ^2.0.0-nullsafety.2
  rxdart: ^0.26.0-nullsafety.0
  http:
    git: https://github.com/dart-lang/http
  flutter_modular: ^3.0.0
  flutter:
    sdk: flutter

dependency_overrydes:
  flutter_modular:
    path: /Users/jacobmoura/Projects/modular/flutter_modular
    
dev_dependencies:
  flutter_modular_test: ^1.0.4
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs