name: mobx_triple
description: Segmented State Pattern for MobX
version: 1.1.3+1
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ">=1.3.0 <2.0.0"
  mobx: ">=2.0.5 <3.0.0"
  triple: ">=1.3.3 <2.0.0"

dev_dependencies:
  test: ^1.16.5



# dependency_overrides:
#   triple: 
#     path: ../triple

