name: flutter_triple
description: Implementation of the Segmented State Pattern (SSP) nicknamed Triple.
version: 2.1.0

repository: https://github.com/Flutterando/triple_pattern/tree/master/stores/flutter_triple
issue_tracker: https://github.com/Flutterando/triple_pattern/issues
homepage: https://triple.flutterando.com.br/
documentation: https://triple.flutterando.com.br/

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  triple: ">=2.0.1 <3.0.0"
  collection: ^1.15.0
  flutter:
    sdk: flutter
  rx_notifier: ">=2.2.0+2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: 0.0.2
  equatable: ^2.0.5
  


flutter:

