# Generated file - do not commit this file.
{
  "name": "triple_test",
  "version": "1.0.0+1",
  "homepage": "https://triple.flutterando.com.br/",
  "documentation": "https://triple.flutterando.com.br/",
  "environment": {
    "sdk": ">=2.12.0 <3.0.0"
  },
  "description": "Test Helper for Store of flutter_triple with Mocktail.",
  "dependencies": {
    "triple": ">=1.0.0 <2.0.0",
    "mocktail": ">=0.1.1 <1.0.0",
    "meta": ">=1.3.0 <2.0.0",
    "test": ">=1.16.0 <2.0.0"
  },
  "dev_dependencies": {
    "flutterando_analysis": "^0.0.1"
  },
  "dependency_overrides": {
    "triple": {
      "path": "..\\\\triple"
    }
  },
  "repository": "https://github.com/Flutterando/triple_pattern",
  "issue_tracker": "https://github.com/Flutterando/triple_pattern/issues"
}