name: triple_test
description: Test Helper for Store of flutter_triple with Mocktail.
version: 0.0.8
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  triple: ">=1.0.0 < 2.0.0"
  mocktail: ^0.1.1
  meta: ^1.3.0
  test: ^1.16.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

